### ISSUE TITLE
Disable our crash reporting

### ISSUE THREAD

**Issue by bauerj** [wo01/electrum-koto#1]
Hey,

we at Electrum recently received a crash report (spesmilo/electrum#3903) from your fork. Since we are not interested in solving issues in your code, we would like you to either disable the crash reporter or switch to your own server.

Thanks in advance.

**Comment by wo01** [comment]
Sorry.
I merged your commit https://github.com/spesmilo/electrum/commit/08b9908f6e9a86162061293e1dad9caf6b14e3e0

**Comment by bauerj** [comment]
Thanks!
