### ISSUE TITLE
<deleted>

### ISSUE THREAD

**Issue by dlilae** [wo01/electrum-koto#21]
-------------------------

**Comment by wo01** [comment]
Electrum Koto does not support private address (z).

This assert message may fix to run kotod with -reindex option

**Comment by dlilae** [comment]
Let's make it so that it does.

Bitcoin Private (zcash clone) supports private address imports too:

https://support.btcprivate.org/403137-Bitcoin-Private-Electrum-Wallet---How-to-sweepimport-Private-Key
